config/routes.rb
SampleApp::Application.routes.draw do
  resources :articles
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  resources :orders
  resources :items
  
  match '/signup2',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/cart',   :to => 'pages#cart'
  match '/help',    :to => 'pages#help'
  root :to => 'pages#home'
  
  
 
  
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <% if signed_in! %>
      <li><%= link_to "Sign up now!", signup2_path, :class => "signup_button round" %></li>
      <% end %>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to shopbanner, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>  
      <% if signed_in? %>
      <li><%= link_to "Own Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "My Orders", orders_path %></li>
      <% if current_user.admin? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Articles", articles_path %></li>
      <% end %>
      <% end %>
      <li><%= link_to "Help", help_path %></li>  
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <Table>
        <tr>
        <td><div><h1><%= title %></h1></div></td>
        <td align="right"><%= link_to logo,cart_path %></td>    
        </tr>
        </Table>

        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>